# Simple workflow for deploying static content to GitHub Pages
name: Create Release

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  create-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # 使用标签名作为 Release 的 tag_name
          release_name: ${{ github.ref_name }} # 使用标签名作为 Release 的名称
          body: |
            自动生成的版本发布。
            请添加一些发行说明！
  
          draft: false # 是否将 Release 设置为草稿，false 表示直接发布
          prerelease: false # 是否为预发布版本，如果是预发行设置为 true
  
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path-to-your-asset.zip
          asset_name: your-asset.zip
          asset_content_type: application/zip
